Resources:
  CognitoAuthorizedApiPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CognitoAuthorizedApiPolicy-${self:custom.stage}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'execute-api:Invoke'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:execute-api:'
                  - Ref: AWS::Region
                  - ':'
                  - Ref: AWS::AccountId
                  - ':'
                  - Ref: RestApi
                  - '/*'
      Roles:
        - 'Fn::ImportValue': CognitoAuthRole-${self:custom.resourcesStage}
  CognitoUnauthorizedApiPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CognitoUnauthorizedApiPolicy-${self:custom.stage}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'execute-api:Invoke'
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:execute-api:'
                    - Ref: AWS::Region
                    - ':'
                    - Ref: AWS::AccountId
                    - ':'
                    - Ref: RestApi
                    - '/*/POST/hello'
      Roles:
        - 'Fn::ImportValue': CognitoUnauthRole-${self:custom.resourcesStage}
